version: '3.8'

services:
  database:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  backend:
    container_name: app
    build:
      context: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

