services:

  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      #      ALTERAR A PORTA PARA NÃO CONFLITAR COM OUTROS SERVIÇOS
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root